config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do

  # Posting and Reading

  resources :aspects do
    get 'manage'                    => :manage, :on => :collection
    put 'toggle_contact_visibility' => :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create, :destroy, :show]
  get 'bookmarklet' => 'status_messages#bookmarklet'
  get 'p/:id'       => 'posts#show', :as => 'post'

  resources :photos, :except => [:index] do
    put 'make_profile_photo' => :make_profile_photo
  end

  resources :comments, :only => [:create, :destroy]

  resources :likes, :only => [:create, :destroy]

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get 'read_all' => :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  get 'tags/:name' => 'tags#show', :as => 'tag'
  
  resources :apps, :only => [:show]
  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :export
    get :export_photos
  end


  controller :users do
    get 'public/:username'          => :public,          :as => 'users_public'
    match 'getting_started'         => :getting_started, :as => 'getting_started'
    get 'getting_started_completed' => :getting_started_completed
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  # generating a new user token (for devise)

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create, :show, :destroy]
  end

  #Temporary token_authenticable route
  resource :token, :only => [:show, :create]

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match 'user_search'   => :user_search
    get   'admin_inviter' => :admin_inviter
    get   'add_invites'   => :add_invites, :as => 'add_invites'
  end

  resource :profile

  resources :contacts,           :except => [:index, :update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only   => [:destroy, :create, :update]
  resources :post_visibilities,  :only   => [:update]

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    post 'by_handle' => :retrieve_remote, :on => :collection, :as => 'person_by_handle'
  end


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    get 'hub'                   => :hub
  end


  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    match '/auth/:provider/callback' => :create
    match '/auth/failure'            => :failure
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    match 'statuses/public_timeline' => :public_timeline
    match 'statuses/home_timeline'   => :home_timeline
    match 'statuses/show/:guid'      => :statuses
    match 'statuses/user_timeline'   => :user_timeline

    match 'users/show'               => :users
    match 'users/search'             => :users_search
    match 'users/profile_image'      => :users_profile_image

    match 'tags_posts/:tag'          => :tag_posts
    match 'tags_people/:tag'         => :tag_people
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'


  # Startpage

  root :to => 'home#show'
end

app/views/notifier/_notifier_css.haml
:css
  body{
    width:600px;
    font-family:'Arial','Helvetica',sans-serif;
    font-size:14px;
    color:#333;
    }
  #container{
    margin-bottom:25px
    min-height:400px;
    padding-left:15px;
  }
  header{
    margin-bottom: 25px;
  }
  p{
    padding:5px;
  }
  p.small{
    font-size:smaller;
    color:#999;
    font-style:italic;
  }
  a{
    color:#107FC9;
    font-weight:bold;
  }
  a:hover{
    color: #22AAE0;
  }
  a:active{
    color: #005D9C;
  }
  .large_text{
    font-size:21px;
    font-family:"Helvetica Neue",Arial,Helvetica,sans-serif;
  }

app/views/notifier/also_commented.html.haml
%p
  = t('notifier.hello', :name => @receiver.profile.first_name)
%p
  = "#{@sender.name} (#{@sender.diaspora_handle})"
  = t('.commented', :post_author => @post_author_name)
  %br
  %br
  = @comment.text

  %br
  %br
  = link_to t('.sign_in'), status_message_url(@comment.post)

  %br
  = t('notifier.love') 
  %br
  = t('notifier.diaspora')

app/views/notifier/also_commented.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)
!= "#{@sender.name} (#{@sender.diaspora_handle})"
!= t('notifier.also_commented.commented', :post_author => @post_author_name)

!= @comment.text

!= "#{t('notifier.love')} \n"
!= t('notifier.diaspora')

app/views/notifier/comment_on_post.html.haml
%p
  = t('notifier.hello', :name => @receiver.profile.first_name)
%p
  = "#{@sender.name} (#{@sender.diaspora_handle})"
  = t('.commented')

  = @comment.text

  %br
  = link_to t('.sign_in'), status_message_url(@comment.post)

  %br
  = t('notifier.love') 
  %br
  = t('notifier.diaspora')

app/views/notifier/comment_on_post.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)
!= "#{@sender.name} (#{@sender.diaspora_handle})"
!= t('notifier.comment_on_post.commented')

!= @comment.text

!= "#{t('notifier.love')} \n"
!= t('notifier.diaspora')

app/views/notifier/liked.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)

!= t('notifier.liked.liked', :name => "#{@sender.name} (#{@sender.diaspora_handle})")

!= @like.post.formatted_message(:plain_text => true)

!= t('notifier.love')
!= t('notifier.diaspora')

app/views/notifier/mentioned.html.haml
%p
  = t('notifier.hello', :name => @receiver.profile.first_name)
%p
  = "#{@sender.name} (#{@sender.diaspora_handle})"
  = t('.mentioned')
%p
  = @post.formatted_message(:plain_text => true)
%p

  %br
  = link_to t('.sign_in'), status_message_url(@post)

  %br
  = t('notifier.love') 
  %br
  = t('notifier.diaspora')

app/views/notifier/mentioned.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)
!= "#{@sender.name} (#{@sender.diaspora_handle})"
!= t('notifier.mentioned.mentioned')

!= @post.formatted_message(:plain_text => true)

!= "#{t('notifier.love')} \n"
!= t('notifier.diaspora')

app/views/notifier/private_message.html.haml
%p
  = t('notifier.hello', :name => @receiver.profile.first_name)
%p
  = "#{@sender.name} (#{@sender.diaspora_handle})"
  = t('.private_message')
%p 
  = t('.message_subject', :subject => @conversation.subject)
%p
  = @message.text
%p

  %br
  = link_to t('.sign_in'), conversations_url(:conversation_id => @conversation)

  %br
  = t('notifier.love') 
  %br
  = t('notifier.diaspora')

app/views/notifier/private_message.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)
!= "#{@sender.name} (#{@sender.diaspora_handle})"
!= t('notifier.private_message.private_message')

!= t('notifier.private_message.message_subject', :subject => @conversation.subject)
!= @message.text

!= "#{t('notifier.love')} \n"
!= t('notifier.diaspora')

app/views/notifier/single_admin.html.haml
%p
  = t('notifier.hello', :name => @receiver.username)
%p
  = @string

  %br
  = t('notifier.thanks')
  = t('notifier.single_admin.admin')

app/views/notifier/single_admin.text.haml
!= t('notifier.hello', :name => @receiver.username)

!= @string

!= t('notifier.thanks')
!= t('notifier.single_admin.admin')

app/views/notifier/started_sharing.html.haml
%p
  = t('notifier.hello', :name => @receiver.profile.first_name)
%p
  = "#{@sender.name} (#{@sender.diaspora_handle})"
  = t('.sharing')

  %br
  = link_to t('.sign_in'), new_user_session_url
  %br
  = t('notifier.love') 
  %br
  = t('notifier.diaspora')

app/views/notifier/started_sharing.text.haml
!= t('notifier.hello', :name => @receiver.profile.first_name)
!= "#{@sender.name} (#{@sender.diaspora_handle})"
!= t('notifier.started_sharing.sharing')

!= t('.sign_in')
!= new_user_session_url
!= "#{t('notifier.love')} \n"
!= t('notifier.diaspora')