config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do

  # Posting and Reading

  resources :aspects do
    get 'manage'                    => :manage, :on => :collection
    put 'toggle_contact_visibility' => :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create, :destroy, :show]
  get 'bookmarklet' => 'status_messages#bookmarklet'
  get 'p/:id'       => 'posts#show', :as => 'post'

  resources :photos, :except => [:index] do
    put 'make_profile_photo' => :make_profile_photo
  end

  resources :comments, :only => [:create, :destroy]

  resources :likes, :only => [:create, :destroy]

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get 'read_all' => :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  get 'tags/:name' => 'tags#show', :as => 'tag'
  
  resources :apps, :only => [:show]
  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :export
    get :export_photos
  end


  controller :users do
    get 'public/:username'          => :public,          :as => 'users_public'
    match 'getting_started'         => :getting_started, :as => 'getting_started'
    get 'getting_started_completed' => :getting_started_completed
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  # generating a new user token (for devise)

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create, :show, :destroy]
  end

  #Temporary token_authenticable route
  resource :token, :only => [:show, :create]

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match 'user_search'   => :user_search
    get   'admin_inviter' => :admin_inviter
    get   'add_invites'   => :add_invites, :as => 'add_invites'
  end

  resource :profile

  resources :contacts,           :except => [:index, :update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only   => [:destroy, :create, :update]
  resources :post_visibilities,  :only   => [:update]

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    post 'by_handle' => :retrieve_remote, :on => :collection, :as => 'person_by_handle'
  end


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    get 'hub'                   => :hub
  end


  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    match '/auth/:provider/callback' => :create
    match '/auth/failure'            => :failure
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    match 'statuses/public_timeline' => :public_timeline
    match 'statuses/home_timeline'   => :home_timeline
    match 'statuses/show/:guid'      => :statuses
    match 'statuses/user_timeline'   => :user_timeline

    match 'users/show'               => :users
    match 'users/search'             => :users_search
    match 'users/profile_image'      => :users_profile_image

    match 'tags_posts/:tag'          => :tag_posts
    match 'tags_people/:tag'         => :tag_people
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'


  # Startpage

  root :to => 'home#show'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  include ROXML
  include Diaspora::Guid
  include Diaspora::Webhooks

  xml_attr :subject
  xml_attr :created_at
  xml_attr :messages, :as => [Message]
  xml_reader :diaspora_handle
  xml_reader :participant_handles

  has_many :conversation_visibilities, :dependent => :destroy
  has_many :participants, :class_name => 'Person', :through => :conversation_visibilities, :source => :person
  has_many :messages, :order => 'created_at ASC'

  belongs_to :author, :class_name => 'Person'

  def self.create(opts={})
    opts = opts.dup
    msg_opts = {:author => opts[:author], :text => opts.delete(:text)}

    cnv = super(opts)
    message = Message.new(msg_opts.merge({:conversation_id => cnv.id}))
    message.save
    cnv
  end

  def recipients
    self.participants - [self.author]
  end

  def diaspora_handle
    self.author.diaspora_handle
  end
  def diaspora_handle= nh
    self.author = Webfinger.new(nh).fetch
  end

  def participant_handles
    self.participants.map{|p| p.diaspora_handle}.join(";")
  end
  def participant_handles= handles
    handles.split(';').each do |handle|
      self.participants << Webfinger.new(handle).fetch
    end
  end

  def last_author
    self.messages.last.author if self.messages.size > 0
  end

  def subject
    self[:subject].blank? ? "no subject" : self[:subject]
  end

  def subscribers(user)
    self.recipients
  end

  def receive(user, person)
    cnv = Conversation.find_or_create_by_guid(self.attributes)

    self.participants.each do |participant|
      ConversationVisibility.find_or_create_by_conversation_id_and_person_id(cnv.id, participant.id)
    end
    self.messages.each do |msg|
      msg.conversation_id = cnv.id
      received_msg = msg.receive(user, person)
      Notification.notify(user, received_msg, person) if msg.respond_to?(:notification_type)
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html, :json, :js

  def index
    @conversations = Conversation.joins(:conversation_visibilities).where(
      :conversation_visibilities => {:person_id => current_user.person.id}).paginate(
      :page => params[:page], :per_page => 15, :order => 'updated_at DESC')

    @visibilities = ConversationVisibility.where(:person_id => current_user.person.id).paginate(
      :page => params[:page], :per_page => 15, :order => 'updated_at DESC')

    @unread_counts = {}
    @visibilities.each { |v| @unread_counts[v.conversation_id] = v.unread }

    @authors = {}
    @conversations.each { |c| @authors[c.id] = c.last_author }

    @conversation = Conversation.joins(:conversation_visibilities).where(
      :conversation_visibilities => {:person_id => current_user.person.id, :conversation_id => params[:conversation_id]}).first
  end

  def create
    person_ids = Contact.where(:id => params[:contact_ids].split(',')).map! do |contact|
      contact.person_id
    end

    params[:conversation][:participant_ids] = person_ids | [current_user.person.id]
    params[:conversation][:author] = current_user.person

    if @conversation = Conversation.create(params[:conversation])
      Postzord::Dispatch.new(current_user, @conversation).post

      flash[:notice] = I18n.t('conversations.create.sent')
      if params[:profile]
        redirect_to person_path(params[:profile])
      else
        redirect_to conversations_path(:conversation_id => @conversation.id)
      end
    end
  end

  def show
    if @conversation = Conversation.joins(:conversation_visibilities).where(:id => params[:id],
                                                                            :conversation_visibilities => {:person_id => current_user.person.id}).first
      if @visibility = ConversationVisibility.where(:conversation_id => params[:id], :person_id => current_user.person.id).first
        @visibility.unread = 0
        @visibility.save
      end

      respond_with @conversation
    else
      redirect_to conversations_path
    end
  end

  def new
    all_contacts_and_ids = Contact.connection.execute(current_user.contacts.joins(:person => :profile
      ).select("contacts.id, profiles.first_name, profiles.last_name, people.diaspora_handle").to_sql).map do |r|
      {:value => r[0],
       :name => Person.name_from_attrs(r[1], r[2], r[3]).gsub(/(")/, "'")}
    end
    @contacts_json = all_contacts_and_ids.to_json.gsub!(/(")/, '\\"')
    @contact = current_user.contacts.find(params[:contact_id]) if params[:contact_id]
    render :layout => false
  end

end

app/views/conversations/_conversation.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%a.conversation{:href => conversation_path(conversation)}
  .stream_element.conversation{:data=>{:guid=>conversation.id}, :class => ('unread' if unread_counts[conversation.id].to_i > 0)}
    = person_image_tag(conversation.author)

    .subject
      .message_count
        = conversation.messages.size

      %div{ :class => direction_for(conversation.subject) }
        = conversation.subject[0..30]

    .last_author
      .timestamp
        = time_ago_in_words(conversation.updated_at)
      = authors[conversation.id].name

      - if conversation.participants.size > 2
        %span.participant_count
          = "(+#{conversation.participants.size - 1})"

app/views/conversations/_show.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


.span-16.last
  .conversation_participants
    .span-9
      %h3{ :class => direction_for(conversation.subject) }
        = conversation.subject

      .conversation_controls
        = link_to (image_tag('reply.png', :height => 14, :width => 14) + ' ' + t('.reply')), '#', :id => 'reply_to_conversation'
        = link_to (image_tag('deletelabel.png') + ' ' + t('.delete').downcase), conversation_visibility_path(conversation), :method => 'delete', :confirm => t('are_you_sure')

    .span-6.avatars.last
      - for participant in conversation.participants
        = person_image_link(participant)

%br
%br
%br
%br
%br
.span-16.last
  .stream
    = render :partial => 'messages/message', :collection => conversation.messages

    .stream_element.new_message
      = owner_image_tag

      .content
        = form_for [conversation, Message.new] do |message|
          = message.text_area :text, :rows => 5
          .right
            = message.submit t('.reply').capitalize, :class => 'button'
            = message.submit t('cancel'), :name => "reset", :id => "reset_button", :type => "reset", :class => "button"

app/views/conversations/index.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :head do
  = include_javascripts :inbox

- content_for :page_title do
  = t('.message_inbox')

:css
  footer{ display:none;}

#left_pane
  #left_pane_header
    %h3
      .right
        = link_to t('.new_message'), new_conversation_path, :class => 'button', :rel => 'facebox'
      = t('.inbox')

  #conversation_inbox
    - if @conversations.count > 0
      .stream.conversations
        = render :partial => 'conversations/conversation', :collection => @conversations, :locals => {:authors => @authors, :unread_counts => @unread_counts}
      = will_paginate @conversations
    - else
      %br
      %br
      %br
      %br
      %div{:style => 'text-align:center;'}
        %i
          = t('.no_messages')

#conversation_show.span-16.prepend-8.last
  - if @conversation
    = render 'conversations/show', :conversation => @conversation
  - else
    #no_conversation_text
      = t('.no_conversation_selected')
    #no_conversation_controls
      = link_to t('.create_a_new_message'), new_conversation_path, :rel => 'facebox'

app/views/conversations/new.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

:javascript
  $(document).ready(function () {
    var data = $.parseJSON( "#{@contacts_json}" ),
        autocompleteInput = $("#contact_autocomplete");

    autocompleteInput.autoSuggest(data, {
      selectedItemProp: "name",
      searchObjProps: "name",
      asHtmlID: "contact_ids",
      retrieveLimit: 10,
      minChars: 3,
      keyDelay: 0,
      startText: '',
      emptyText: '#{t('no_results')}',
      preFill: [{ 'name' : "#{params[:name]}",
                 'value' : "#{params[:contact_id]}"}]
      });

    autocompleteInput.focus();
  });


#new_message_pane
  .span-12.last
    #facebox_header
      %h4
        = t('conversations.index.new_message')

    = form_for Conversation.new do |conversation|
      %br

      .span-2
        %h4
          = t('.to')
      .span-10.last
        = text_field_tag "contact_autocomplete"
      .clearfix

      .span-2
        %h4
          = t('.subject')
      .span-10.last
        = conversation.text_field :subject

      .span-10.prepend-2.last
        = text_area_tag "conversation[text]", '', :rows => 5

      .text-right
        = conversation.submit t('.send'), :disable_with => t('shared.publisher.posting'), :class => 'button'
        = link_to t('cancel'), conversations_path

app/views/conversations/show.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'show', :conversation => @conversation

app/views/conversations/show.js.erb
$('#conversation_show').html("<%= escape_javascript(render('conversations/show', :conversation => @conversation)) %>");

$(".stream_element", "#conversation_inbox").removeClass('selected');
$(".stream_element[data-guid='<%= @conversation.id %>']", "#conversation_inbox").addClass('selected');

Diaspora.widgets.timeago.updateTimeAgo();