config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do

  # Posting and Reading

  resources :aspects do
    get 'manage'                    => :manage, :on => :collection
    put 'toggle_contact_visibility' => :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create, :destroy, :show]
  get 'bookmarklet' => 'status_messages#bookmarklet'
  get 'p/:id'       => 'posts#show', :as => 'post'

  resources :photos, :except => [:index] do
    put 'make_profile_photo' => :make_profile_photo
  end

  resources :comments, :only => [:create, :destroy]

  resources :likes, :only => [:create, :destroy]

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get 'read_all' => :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  get 'tags/:name' => 'tags#show', :as => 'tag'
  
  resources :apps, :only => [:show]
  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :export
    get :export_photos
  end


  controller :users do
    get 'public/:username'          => :public,          :as => 'users_public'
    match 'getting_started'         => :getting_started, :as => 'getting_started'
    get 'getting_started_completed' => :getting_started_completed
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  # generating a new user token (for devise)

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create, :show, :destroy]
  end

  #Temporary token_authenticable route
  resource :token, :only => [:show, :create]

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match 'user_search'   => :user_search
    get   'admin_inviter' => :admin_inviter
    get   'add_invites'   => :add_invites, :as => 'add_invites'
  end

  resource :profile

  resources :contacts,           :except => [:index, :update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only   => [:destroy, :create, :update]
  resources :post_visibilities,  :only   => [:update]

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    post 'by_handle' => :retrieve_remote, :on => :collection, :as => 'person_by_handle'
  end


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    get 'hub'                   => :hub
  end


  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    match '/auth/:provider/callback' => :create
    match '/auth/failure'            => :failure
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    match 'statuses/public_timeline' => :public_timeline
    match 'statuses/home_timeline'   => :home_timeline
    match 'statuses/show/:guid'      => :statuses
    match 'statuses/user_timeline'   => :user_timeline

    match 'users/show'               => :users
    match 'users/search'             => :users_search
    match 'users/profile_image'      => :users_profile_image

    match 'tags_posts/:tag'          => :tag_posts
    match 'tags_people/:tag'         => :tag_people
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'


  # Startpage

  root :to => 'home#show'
end

app/models/post.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Post < ActiveRecord::Base
  require File.join(Rails.root, 'lib/diaspora/web_socket')
  include ApplicationHelper
  include ROXML
  include Diaspora::Webhooks
  include Diaspora::Guid

  xml_attr :diaspora_handle
  xml_attr :public
  xml_attr :created_at

  has_many :comments, :order => 'created_at ASC'
  has_many :likes, :conditions => {:positive => true}, :dependent => :delete_all
  has_many :dislikes, :conditions => {:positive => false}, :class_name => 'Like', :dependent => :delete_all

  has_many :aspect_visibilities
  has_many :aspects, :through => :aspect_visibilities

  has_many :post_visibilities
  has_many :contacts, :through => :post_visibilities
  has_many :mentions, :dependent => :destroy

  belongs_to :author, :class_name => 'Person'

  cattr_reader :per_page
  @@per_page = 10

  def diaspora_handle
    read_attribute(:diaspora_handle) || self.author.diaspora_handle
  end
  def user_refs
    if AspectVisibility.exists?(:post_id => self.id)
      self.post_visibilities.count + 1
    else
      self.post_visibilities.count
    end
  end

  def diaspora_handle= nd
    self.author = Person.where(:diaspora_handle => nd).first
    write_attribute(:diaspora_handle, nd)
  end

  def self.diaspora_initialize params
    new_post = self.new params.to_hash
    new_post.author = params[:author]
    new_post.public = params[:public] if params[:public]
    new_post.pending = params[:pending] if params[:pending]
    new_post.diaspora_handle = new_post.author.diaspora_handle
    new_post
  end

  def as_json(opts={})
    {
        :post => {
            :id     => self.guid,
            :author => self.author.as_json,
        }
    }
  end

  def mutable?
    false
  end

  def subscribers(user)
    if self.public?
      user.contact_people
    else
      user.people_in_aspects(user.aspects_with_post(self.id))
    end
  end

  def receive(user, person)
    #exists locally, but you dont know about it
    #does not exsist locally, and you dont know about it
    #exists_locally?
    #you know about it, and it is mutable
    #you know about it, and it is not mutable

    local_post = Post.where(:guid => self.guid).first
    if local_post && local_post.author_id == self.author_id
      known_post = user.visible_posts.where(:guid => self.guid).first
      if known_post
        if known_post.mutable?
          known_post.update_attributes(self.attributes)
        else
          Rails.logger.info("event=receive payload_type=#{self.class} update=true status=abort sender=#{self.diaspora_handle} reason=immutable existing_post=#{known_post.id}")
        end
      else
        user.contact_for(person).receive_post(local_post)
        user.notify_if_mentioned(local_post)
        Rails.logger.info("event=receive payload_type=#{self.class} update=true status=complete sender=#{self.diaspora_handle} existing_post=#{local_post.id}")
        return local_post
      end
    elsif !local_post
      if self.save
        user.contact_for(person).receive_post(self)
        user.notify_if_mentioned(self)
        Rails.logger.info("event=receive payload_type=#{self.class} update=false status=complete sender=#{self.diaspora_handle}")
        return self
      else
        Rails.logger.info("event=receive payload_type=#{self.class} update=false status=abort sender=#{self.diaspora_handle} reason=#{self.errors.full_messages}")
      end
    else
      Rails.logger.info("event=receive payload_type=#{self.class} update=true status=abort sender=#{self.diaspora_handle} reason='update not from post owner' existing_post=#{self.id}")
    end
  end

  def activity_streams?
    false
  end
end

app/models/status_message.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class StatusMessage < Post
  include Diaspora::Socketable
  include Diaspora::Taggable

  include YoutubeTitles
  require File.join(Rails.root, 'lib/youtube_titles')
  include ActionView::Helpers::TextHelper

  acts_as_taggable_on :tags
  extract_tags_from :raw_message

  validates_length_of :text, :maximum => 10000, :message => I18n.t('status_messages.too_long', :count => 10000)
  xml_name :status_message
  xml_attr :raw_message

  has_many :photos, :dependent => :destroy, :foreign_key => :status_message_guid, :primary_key => :guid
  validate :message_or_photos_present?

  attr_accessible :text

  serialize :youtube_titles, Hash
  before_save do
    get_youtube_title text
  end

  before_create :build_tags

  def text(opts = {})
    self.formatted_message(opts)
  end

  def raw_message
    read_attribute(:text)
  end
  def raw_message=(text)
    write_attribute(:text, text)
  end

  def formatted_message(opts={})
    return self.raw_message unless self.raw_message

    escaped_message = opts[:plain_text] ? self.raw_message: ERB::Util.h(self.raw_message)
    mentioned_message = self.format_mentions(escaped_message, opts)
    self.format_tags(mentioned_message, opts)
  end

  def format_mentions(text, opts = {})
    people = self.mentioned_people
    regex = /@\{([^;]+); ([^\}]+)\}/
    form_message = text.gsub(regex) do |matched_string|
      person = people.detect{ |p|
        p.diaspora_handle == $~[2] unless p.nil?
      }

      if opts[:plain_text]
        person ? ERB::Util.h(person.name) : ERB::Util.h($~[1])
      else
        person ? "<a href=\"/people/#{person.id}\" class=\"mention\">@#{ERB::Util.h(person.name)}</a>" : ERB::Util.h($~[1])
      end
    end
    form_message
  end

  def mentioned_people
    if self.persisted?
      create_mentions if self.mentions.empty?
      self.mentions.includes(:person => :profile).map{ |mention| mention.person }
    else
      mentioned_people_from_string
    end
  end

  def create_mentions
    mentioned_people_from_string.each do |person|
      self.mentions.create(:person => person)
    end
  end

  def mentions?(person)
    mentioned_people.include? person
  end

  def notify_person(person)
    self.mentions.where(:person_id => person.id).first.try(:notify_recipient)
  end

  def mentioned_people_from_string
    regex = /@\{([^;]+); ([^\}]+)\}/
    identifiers = self.raw_message.scan(regex).map do |match|
      match.last
    end
    identifiers.empty? ? [] : Person.where(:diaspora_handle => identifiers)
  end

  def to_activity
    <<-XML
  <entry>
    <title>#{x(self.formatted_message(:plain_text => true))}</title>
    <content>#{x(self.formatted_message(:plain_text => true))}</content>
    <link rel="alternate" type="text/html" href="#{self.author.url}p/#{self.id}"/>
    <id>#{self.author.url}p/#{self.id}</id>
    <published>#{self.created_at.xmlschema}</published>
    <updated>#{self.updated_at.xmlschema}</updated>
    <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  </entry>
      XML
  end

  def as_json(opts={})
    opts ||= {}
    if(opts[:format] == :twitter)
      {
        :id => self.guid,
        :text => self.formatted_message(:plain_text => true),
        :entities => {
            :urls => [],
            :hashtags => self.tag_list,
            :user_mentions => self.mentioned_people.map{|p| p.diaspora_handle},
          },
        :source => 'diaspora',
        :created_at => self.created_at,
        :user => self.author.as_json(opts)
      }
    else
      super(opts)
    end
  end

  def socket_to_user(user_or_id, opts={})
    unless opts[:aspect_ids]
      user_id = user_or_id.instance_of?(Fixnum) ? user_or_id : user_or_id.id
      aspect_ids = AspectMembership.connection.execute(
        AspectMembership.joins(:contact).where(:contacts => {:user_id => user_id, :person_id => self.author_id}).select('aspect_memberships.aspect_id').to_sql
      ).map{|r| r.first}
      opts.merge!(:aspect_ids => aspect_ids)
    end
    super(user_or_id, opts)
  end

  protected

  def message_or_photos_present?
    if self.text.blank? && self.photos == []
      errors[:base] << 'Status message requires a message or at least one photo'
    end
  end
end

app/controllers/status_messages_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class StatusMessagesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :mobile
  respond_to :json, :only => :show

  def new
    @person = Person.find(params[:person_id])
    @aspect = :profile
    @contact = current_user.contact_for(@person)
    @aspects_with_person = []
    if @contact
      @aspects_with_person = @contact.aspects
      @aspect_ids = @aspects_with_person.map(&:id)
      @contacts_of_contact = @contact.contacts

      render :layout => nil
    else
      redirect_to :back
    end
  end

  def bookmarklet
    @aspects = current_user.aspects
    @selected_contacts = @aspects.map { |aspect| aspect.contacts }.flatten.uniq
    @aspect_ids = @aspects.map{|x| x.id}
    render :layout => nil
  end

  def create
    params[:status_message][:aspect_ids] = params[:aspect_ids]

    photos = Photo.where(:id => [*params[:photos]], :diaspora_handle => current_user.person.diaspora_handle)

    public_flag = params[:status_message][:public]
    public_flag.to_s.match(/(true)|(on)/) ? public_flag = true : public_flag = false
    params[:status_message][:public] = public_flag

    @status_message = current_user.build_post(:status_message, params[:status_message])
    aspects = current_user.aspects_from_ids(params[:aspect_ids])

    if !photos.empty?
      @status_message.photos << photos
    end
    if @status_message.save
      Rails.logger.info("event=create type=status_message chars=#{params[:status_message][:text].length}")

      current_user.add_to_streams(@status_message, aspects)
      receiving_services = params[:services].map{|s| current_user.services.where(
                                  :type => "Services::"+s.titleize).first} if params[:services]
      current_user.dispatch_post(@status_message, :url => post_url(@status_message), :services => receiving_services)
      if !photos.empty?
        for photo in photos
          was_pending = photo.pending
          if was_pending
            current_user.add_to_streams(photo, aspects)
            current_user.dispatch_post(photo)
          end
        end
        photos.update_all(:pending => false, :public => public_flag)
      end

      if request.env['HTTP_REFERER'].include?("people")
        flash[:notice] = t('status_messages.create.success', :names => @status_message.mentions.includes(:person => :profile).map{ |mention| mention.person.name }.join(', '))
      end

      respond_to do |format|
        format.js { render :create, :status => 201}
        format.html { redirect_to :back}
        format.mobile{ redirect_to root_url}
      end
    else
      if !photos.empty?
        photos.update_all(:status_message_guid => nil)
      end
      respond_to do |format|
        format.js { 
          errors = @status_message.errors.full_messages.collect { |msg| msg.gsub(/^Text/, "") }
          render :json =>{:errors => errors}, :status => 422
        }
        format.html {redirect_to :back}
      end
    end
  end

  def destroy
    @status_message = current_user.posts.where(:id => params[:id]).first
    if @status_message
      current_user.retract(@status_message)
      respond_to do |format|
        format.js {render 'destroy'}
        format.all {redirect_to root_url}
      end
    else
      Rails.logger.info "event=post_destroy status=failure user=#{current_user.diaspora_handle} reason='User does not own post'"
      render :nothing => true, :status => 404
    end
  end

  def show
    @status_message = current_user.find_visible_post_by_id params[:id]
    if @status_message
      @object_aspect_ids = @status_message.aspects.map{|a| a.id}

      # mark corresponding notification as read
      if notification = Notification.where(:recipient_id => current_user.id, :target_id => @status_message.id).first
        notification.unread = false
        notification.save
      end

      respond_with @status_message
    else
      Rails.logger.info(:event => :link_to_nonexistent_post, :ref => request.env['HTTP_REFERER'], :user_id => current_user.id, :post_id => params[:id])
      flash[:error] = I18n.t('status_messages.show.not_found')
      redirect_to :back
    end
  end

end

app/helpers/status_messages_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module StatusMessagesHelper
  def my_latest_message
    unless @latest_status_message.nil?
      return @latest_status_message.text
    else
      return I18n.t('status_messages.helper.no_message_to_display')
    end
  end
end

app/views/status_messages/_status_message.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- if photos.size > 0
  .photo_attachments
    = link_to (image_tag photos.first.url(:scaled_full)), photo_path(photos.first)
    - if photos.size > 1
      - if photos.size >= 8
        - for photo in photos[1..8]
          = link_to (image_tag photo.url(:thumb_small), :class => 'thumb_small'), photo_path(photo)
      - else
        - for photo in photos[1..photos.size]
          = link_to (image_tag photo.url(:thumb_small), :class => 'thumb_small'), photo_path(photo)

%p{ :class => direction_for(post.text) }
  = markdownify(post.text, :youtube_maps => post[:youtube_titles])

app/views/status_messages/bookmarklet.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= include_javascripts :jquery
= include_javascripts :main
= include_stylesheets :default, :media => 'all'
= stylesheet_link_tag "blueprint/screen", :media => 'screen'
= javascript_include_tag "publisher.js"

:javascript
  Diaspora.widgets.i18n.loadLocale(#{get_javascript_strings_for(current_user.language).to_json}, "#{current_user.language}");
  $(document).ready(function() 
    {
      Publisher.open();
      $("#publisher").bind('ajax:success', function(){
        $('h4').text("#{t('bookmarklet.post_success')}");
        Publisher.close();

        window.setTimeout(window.close, 2000, true);
      });

      var contents = "#{params[:title]} - #{params[:url]}";
      if ("#{params[:notes]}".length > 0){
        contents = contents + " - #{params[:notes]}";
      }
      
      $("#publisher #status_message_fake_text").val(contents);
      $("#publisher #status_message_text").val(contents);
      $('input.button')[0].removeAttribute('disabled');
  });

#new_status_message_pane
  .span-15.last
    #facebox_header
      %h4
        =t('bookmarklet.post_something')

    = render :partial => 'shared/publisher', :locals => { :aspect => :profile, :aspects_with_person => @aspects,  :aspect_ids => @aspect_ids}

app/views/status_messages/create.js.erb
<%= {:html =>  render(
    :partial => 'shared/stream_element',
    :locals => {
      :post => @status_message,
      :author => @status_message.author,
      :photos => @status_message.photos,
      :comments => [],
      :all_aspects => current_user.aspects
    }
  ),
  :post_id => @status_message.id}.to_json.html_safe%>

app/views/status_messages/destroy.js.erb
var target = $(".stream_element[data-guid=<%= escape_javascript(@status_message.id.to_s) %>]")
target.hide('blind', { direction: 'vertical' }, 300, function(){ target.remove() });

app/views/status_messages/new.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= javascript_include_tag "publisher.js"

:javascript
  $(document).ready(function() 
    {
      var person = {name: '#{@person.name}', handle: '#{@person.diaspora_handle}' };
      Publisher.autocompletion.onSelect($("#status_message_fake_text"),person,'#{@person.name}');
      $("#publisher #status_message_fake_text").val(function(index, value){ return value + " " });
      $("#publisher").bind('ajax:success', function(){location.reload();});
      Publisher.open();
    });

#new_status_message_pane
  .span-15.last
    #facebox_header
      %h4
        = t('.mentioning', :person => @person.name)

    = render :partial => 'shared/publisher', :locals => { :aspect => @aspect, :aspect_ids => @aspect_ids, :aspects_with_person => @aspects_with_person, :person => @person}

app/views/status_messages/show.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


.span-16.append-4.prepend-4.last
  #original_post_info
    = render 'shared/author_info', :person => @status_message.author, :post => @status_message

  #show_text
    %p
      = markdownify(@status_message.text, :youtube_maps => @status_message[:youtube_titles])

    - for photo in @status_message.photos
      = link_to (image_tag photo.url(:thumb_small), :class => 'thumb_small'), photo_path(photo)

  %p.time
    = how_long_ago(@status_message)

  %hr

  = link_to t('.permalink'), post_path(@status_message) if @status_message.public
  %br
  - if current_user.owns? @status_message
    = link_to t('.destroy'), @status_message, :confirm => t('are_you_sure'), :method => :delete


  %h5
    = t('_comments')
  #status_message_stream.stream.show
    %div{:data=>{:guid=>@status_message.id}}
      = render "comments/comments", :post => @status_message, :comments => @status_message.comments, :always_expanded => true

app/views/status_messages/show.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#show_content{:data=>{:guid=>@status_message.id}}
  = render 'shared/author_info', :person => @status_message.author, :post => @status_message

  %p
    = markdownify(@status_message.text, :youtube_maps => @status_message[:youtube_titles])

  - for photo in @status_message.photos
    = link_to (image_tag photo.url(:thumb_small), :class => 'thumb_small'), photo.url(:thumb_medium)

  .info
    %span.time
      = t('ago', :time => time_ago_in_words(@status_message.created_at))

      %br
      - if current_user.owns? @status_message
        = link_to t('delete'), @status_message, :confirm => t('are_you_sure'), :method => :delete
      - else
        = link_to t('hide'), post_visibility_path(:id => "42", :post_id => @status_message.id), :confirm => t('are_you_sure'), :method => :put, :remote => true

.stream.show{:data=>{:guid=>@status_message.id}}
  = render "comments/comments", :post => @status_message, :comments => @status_message.comments, :always_expanded => true