config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do

  # Posting and Reading

  resources :aspects do
    get 'manage'                    => :manage, :on => :collection
    put 'toggle_contact_visibility' => :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create, :destroy, :show]
  get 'bookmarklet' => 'status_messages#bookmarklet'
  get 'p/:id'       => 'posts#show', :as => 'post'

  resources :photos, :except => [:index] do
    put 'make_profile_photo' => :make_profile_photo
  end

  resources :comments, :only => [:create, :destroy]

  resources :likes, :only => [:create, :destroy]

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get 'read_all' => :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  get 'tags/:name' => 'tags#show', :as => 'tag'
  
  resources :apps, :only => [:show]
  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :export
    get :export_photos
  end


  controller :users do
    get 'public/:username'          => :public,          :as => 'users_public'
    match 'getting_started'         => :getting_started, :as => 'getting_started'
    get 'getting_started_completed' => :getting_started_completed
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  # generating a new user token (for devise)

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create, :show, :destroy]
  end

  #Temporary token_authenticable route
  resource :token, :only => [:show, :create]

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match 'user_search'   => :user_search
    get   'admin_inviter' => :admin_inviter
    get   'add_invites'   => :add_invites, :as => 'add_invites'
  end

  resource :profile

  resources :contacts,           :except => [:index, :update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only   => [:destroy, :create, :update]
  resources :post_visibilities,  :only   => [:update]

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    post 'by_handle' => :retrieve_remote, :on => :collection, :as => 'person_by_handle'
  end


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    get 'hub'                   => :hub
  end


  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    match '/auth/:provider/callback' => :create
    match '/auth/failure'            => :failure
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    match 'statuses/public_timeline' => :public_timeline
    match 'statuses/home_timeline'   => :home_timeline
    match 'statuses/show/:guid'      => :statuses
    match 'statuses/user_timeline'   => :user_timeline

    match 'users/show'               => :users
    match 'users/search'             => :users_search
    match 'users/profile_image'      => :users_profile_image

    match 'tags_posts/:tag'          => :tag_posts
    match 'tags_people/:tag'         => :tag_people
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'


  # Startpage

  root :to => 'home#show'
end

app/models/aspect.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Aspect < ActiveRecord::Base
  belongs_to :user

  has_many :aspect_memberships, :dependent => :destroy
  has_many :contacts, :through => :aspect_memberships

  has_many :aspect_visibilities
  has_many :posts, :through => :aspect_visibilities

  validates_presence_of :name
  validates_length_of :name, :maximum => 20
  validates_uniqueness_of :name, :scope => :user_id, :case_sensitive => false

  attr_accessible :name, :contacts_visible

  before_validation do
    name.strip!
  end

  def to_s
    name
  end
end

app/models/post.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Post < ActiveRecord::Base
  require File.join(Rails.root, 'lib/diaspora/web_socket')
  include ApplicationHelper
  include ROXML
  include Diaspora::Webhooks
  include Diaspora::Guid

  xml_attr :diaspora_handle
  xml_attr :public
  xml_attr :created_at

  has_many :comments, :order => 'created_at ASC'
  has_many :likes, :conditions => {:positive => true}, :dependent => :delete_all
  has_many :dislikes, :conditions => {:positive => false}, :class_name => 'Like', :dependent => :delete_all

  has_many :aspect_visibilities
  has_many :aspects, :through => :aspect_visibilities

  has_many :post_visibilities
  has_many :contacts, :through => :post_visibilities
  has_many :mentions, :dependent => :destroy

  belongs_to :author, :class_name => 'Person'

  cattr_reader :per_page
  @@per_page = 10

  def diaspora_handle
    read_attribute(:diaspora_handle) || self.author.diaspora_handle
  end
  def user_refs
    if AspectVisibility.exists?(:post_id => self.id)
      self.post_visibilities.count + 1
    else
      self.post_visibilities.count
    end
  end

  def diaspora_handle= nd
    self.author = Person.where(:diaspora_handle => nd).first
    write_attribute(:diaspora_handle, nd)
  end

  def self.diaspora_initialize params
    new_post = self.new params.to_hash
    new_post.author = params[:author]
    new_post.public = params[:public] if params[:public]
    new_post.pending = params[:pending] if params[:pending]
    new_post.diaspora_handle = new_post.author.diaspora_handle
    new_post
  end

  def as_json(opts={})
    {
        :post => {
            :id     => self.guid,
            :author => self.author.as_json,
        }
    }
  end

  def mutable?
    false
  end

  def subscribers(user)
    if self.public?
      user.contact_people
    else
      user.people_in_aspects(user.aspects_with_post(self.id))
    end
  end

  def receive(user, person)
    #exists locally, but you dont know about it
    #does not exsist locally, and you dont know about it
    #exists_locally?
    #you know about it, and it is mutable
    #you know about it, and it is not mutable

    local_post = Post.where(:guid => self.guid).first
    if local_post && local_post.author_id == self.author_id
      known_post = user.visible_posts.where(:guid => self.guid).first
      if known_post
        if known_post.mutable?
          known_post.update_attributes(self.attributes)
        else
          Rails.logger.info("event=receive payload_type=#{self.class} update=true status=abort sender=#{self.diaspora_handle} reason=immutable existing_post=#{known_post.id}")
        end
      else
        user.contact_for(person).receive_post(local_post)
        user.notify_if_mentioned(local_post)
        Rails.logger.info("event=receive payload_type=#{self.class} update=true status=complete sender=#{self.diaspora_handle} existing_post=#{local_post.id}")
        return local_post
      end
    elsif !local_post
      if self.save
        user.contact_for(person).receive_post(self)
        user.notify_if_mentioned(self)
        Rails.logger.info("event=receive payload_type=#{self.class} update=false status=complete sender=#{self.diaspora_handle}")
        return self
      else
        Rails.logger.info("event=receive payload_type=#{self.class} update=false status=abort sender=#{self.diaspora_handle} reason=#{self.errors.full_messages}")
      end
    else
      Rails.logger.info("event=receive payload_type=#{self.class} update=true status=abort sender=#{self.diaspora_handle} reason='update not from post owner' existing_post=#{self.id}")
    end
  end

  def activity_streams?
    false
  end
end

app/controllers/aspects_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class AspectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :save_sort_order, :only => :index
  before_filter :ensure_page, :only => :index

  respond_to :html, :js
  respond_to :json, :only => [:show, :create]

  def index
    if params[:a_ids]
      @aspects = current_user.aspects.where(:id => params[:a_ids])
    else
      @aspects = current_user.aspects
      @contacts_sharing_with = current_user.contacts.sharing
    end

    #No aspect_listings on infinite scroll
    @aspects = @aspects.includes(:contacts => {:person => :profile}) unless params[:only_posts]

    # redirect to signup
    if (current_user.getting_started == true || @aspects.blank?) && !request.format.mobile? && !request.format.js?
      redirect_to getting_started_path
      return
    end

    @selected_contacts = @aspects.map { |aspect| aspect.contacts }.flatten.uniq unless params[:only_posts]

    @aspect_ids = @aspects.map { |a| a.id }
    posts = current_user.visible_posts(:by_members_of => @aspect_ids,
                                           :type => ['StatusMessage','ActivityStreams::Photo'],
                                           :order => session[:sort_order] + ' DESC',
                                           :max_time => params[:max_time].to_i
                          ).includes(:comments, :mentions, :likes, :dislikes)

    @posts = PostsFake.new(posts)
    if params[:only_posts]
      render :partial => 'shared/stream', :locals => {:posts => @posts}
    else
      @contact_count = current_user.contacts.count

      @aspect = :all unless params[:a_ids]
      @aspect ||= @aspects.first # used in mobile
    end
  end

  def create
    @aspect = current_user.aspects.create(params[:aspect])

    if @aspect.valid?
      flash[:notice] = I18n.t('aspects.create.success', :name => @aspect.name)
      if current_user.getting_started
        redirect_to :back
      elsif request.env['HTTP_REFERER'].include?("aspects/manage")
        redirect_to :back
      elsif params[:aspect][:person_id]
        @person = Person.where(:id => params[:aspect][:person_id]).first

        if @contact = current_user.contact_for(@person)
          @contact.aspects << @aspect
        else
          @contact = current_user.share_with(@person, @aspect)
        end



      else
        respond_with @aspect
      end
    else
      respond_to do |format|
        format.js { render :text => I18n.t('aspects.create.failure'), :status => 422 }
        format.html do
          flash[:error] = I18n.t('aspects.create.failure')
          redirect_to :back
        end
      end
    end
  end

  def new
    @aspect = Aspect.new
    @person_id = params[:person_id]
    render :layout => false
  end

  def destroy
    @aspect = current_user.aspects.where(:id => params[:id]).first

    begin
      @aspect.destroy
      flash[:notice] = I18n.t 'aspects.destroy.success', :name => @aspect.name
      redirect_to aspects_path
    rescue ActiveRecord::StatementInvalid => e
      flash[:error] = I18n.t 'aspects.destroy.failure', :name => @aspect.name
      redirect_to aspects_path
    end
  end

  def show
    @aspect = current_user.aspects.where(:id => params[:id]).first
    if @aspect
      redirect_to aspects_path('a_ids[]' => @aspect.id)
    else
      redirect_to aspects_path
    end
  end

  def edit
    @aspect = current_user.aspects.where(:id => params[:id]).includes(:contacts => {:person => :profile}).first

    @contacts_in_aspect = @aspect.contacts.includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    c = Contact.arel_table
    if @contacts_in_aspect.empty?
      @contacts_not_in_aspect = current_user.contacts.receiving.includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    else
      @contacts_not_in_aspect = current_user.contacts.receiving.where(c[:id].not_in(@contacts_in_aspect.map(&:id))).includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    end

    @contacts = @contacts_in_aspect + @contacts_not_in_aspect

    unless @aspect
      render :file => "#{Rails.root}/public/404.html", :layout => false, :status => 404
    else
      @aspect_ids = [@aspect.id]
      @aspect_contacts_count = @aspect.contacts.size
      render :layout => false
    end
  end

  def manage
    @aspect = :manage
    @contacts = current_user.contacts.includes(:person => :profile)
    @aspects = @all_aspects.includes(:contacts => {:person => :profile})
  end

  def update
    @aspect = current_user.aspects.where(:id => params[:id]).first

    if @aspect.update_attributes!(params[:aspect])
      flash[:notice] = I18n.t 'aspects.update.success', :name => @aspect.name
    else
      flash[:error] = I18n.t 'aspects.update.failure', :name => @aspect.name
    end
    render :nothing => true, :status => 204
  end

  def toggle_contact_visibility
    @aspect = current_user.aspects.where(:id => params[:aspect_id]).first

    if @aspect.contacts_visible?
      @aspect.contacts_visible = false
    else
      @aspect.contacts_visible = true
    end
    @aspect.save
  end

  def ensure_page
    params[:max_time] ||= Time.now + 1
  end

  private
  def save_sort_order
    if params[:sort_order].present?
      session[:sort_order] = (params[:sort_order] == 'created_at') ? 'created_at' : 'updated_at'
    elsif session[:sort_order].blank?
      session[:sort_order] = 'updated_at'
    else
      session[:sort_order] = (session[:sort_order] == 'created_at') ? 'created_at' : 'updated_at'
    end
  end

end

app/helpers/aspects_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module AspectsHelper
  def remove_link(aspect)
    if aspect.contacts.size == 0
      link_to I18n.t('aspects.helper.remove'), aspect, :method => :delete, :confirm => I18n.t('aspects.helper.are_you_sure')
    else
      "<span class='grey' title=#{I18n.t('aspects.helper.aspect_not_empty')}>#{I18n.t('aspects.helper.remove')}</span>"
    end
  end

  def add_to_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_plus_add_round.png'),
      {:controller => 'aspect_memberships',
        :action => 'create',
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :method => 'post',
      :class => 'add button',
      'data-aspect_id' => aspect_id,
      'data-person_id' => person_id
  end

  def remove_from_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_check_yes.png'),
      {:controller => "aspect_memberships",
        :action => 'destroy',
        :id => 42,
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :method => 'delete',
      :class => 'added button',
      'data-aspect_id' => aspect_id,
      'data-person_id' => person_id
  end

  def aspect_membership_button(aspect, contact, person)
    if contact.nil? || !contact.aspect_memberships.detect{ |am| am.aspect_id == aspect.id}
      add_to_aspect_button(aspect.id, person.id)
    else
      remove_from_aspect_button(aspect.id, person.id)
    end
  end
end

app/views/aspects/_aspect_contacts.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  =javascript_include_tag 'aspect-contacts'
  :javascript
    EditPane.setTranslations({
      doneEditing: "#{t('.done_editing')}",
      editAspect:"#{t('aspects.show.edit_aspect')}"
    });

  - if aspect.contacts.count == 0
    :javascript
      $(document).ready(function(){
        EditPane.fadeIn();
      });

#left_pane
  .section.contact_pictures
    - for contact in contacts
      = person_image_link(contact[:person])

    %br
    %br
    %br
    .section
      %h3= t('shared.invitations.invites')
      = render "shared/invitations", :invites => @invites

app/views/aspects/_aspect_list_item.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li{:data=>{:guid=>aspect.id}}
  %span.name
    = link_to aspect.name, aspect
  .right
    = aspect_membership_button(aspect, contact, person)

app/views/aspects/_aspect_listings.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%h4
  .right
    = link_to t('contacts', :count => @contact_count), manage_aspects_path, :title => t('aspects.manage.manage_aspects')

  = t('aspects', :count => aspects.count)

%ul
  - for aspect in aspects
    = render 'aspects/aspect', :aspect => aspect, :contacts => aspect.contacts

  - if @contacts_sharing_with
    %li#sharers{:class => ("dull" if @contacts_sharing_with.size == 0)}
      .right
        %b
          = link_to t('contacts', :count => @contacts_sharing_with.size), sharing_contacts_path, :rel => 'facebox', :class => 'contact-count'
      %b
        = t('aspects.index.people_sharing_with_you')
      %br

      - if @contacts_sharing_with.size > 0
        .contacts
          - for contact in @contacts_sharing_with[0..15]
            = person_image_link(contact.person)

app/views/aspects/_aspect_stream.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'shared/publisher', :aspect => aspect, :aspect_ids => aspect_ids
#sort_by
  = t('.sort_by')
  = link_to_if(session[:sort_order] == 'created_at', t('.activity'), aspects_path(:a_ids => params[:a_ids], :sort_order => 'updated_at'))
  |
  = link_to_if(session[:sort_order] == 'updated_at', t('.post_time'), aspects_path(:a_ids => params[:a_ids], :sort_order => 'created_at' ))
#main_stream.stream{:data => {:guids => aspect_ids.join(',')}}
  - if posts.length > 0
    = render 'shared/stream', :posts => posts
    #pagination
      =link_to(t('more'), next_page_path, :class => 'paginate')
  - else
    = render 'aspects/no_posts_message', :post_count => posts.length

app/views/aspects/_edit_aspect_pane.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  = include_javascripts :aspects

#edit_aspect_pane
  - if @contacts.count > 0
    %h4= t('aspects.edit.add_existing')
    = render 'shared/contact_list', :aspect_id => aspect.id, :contacts => contacts, :manage => defined?(manage)

  = render 'shared/add_contact', :aspect_id => aspect.id

  %hr
  = form_for aspect do |asp|
    = asp.text_field :name, :value => aspect.name
    = t('aspects.contacts_visible')
    = aspect.check_box :contacts_visible, :default => true
    %br
    = t('aspects.contacts_not_visible')
    -#contacts_visible should be editable here
    = asp.submit t('aspects.edit.rename_aspect')

  %hr
  .big_buttons
    = button_to t('aspects.edit.remove_aspect'), aspect, :method => "delete", :confirm => t('aspects.edit.confirm_remove_aspect')

app/views/aspects/_new.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-12.last
  #facebox_header
    %h4
      = t('aspects.manage.add_a_new_aspect')

  = form_for(Aspect.new, :remote => (defined?(remote) && remote) ) do |aspect|
    = aspect.error_messages
    - if defined?(person_id)
      = aspect.hidden_field :person_id, :value => person_id
    %p
      = aspect.label :name , t('.name')
      = aspect.text_field :name, :maxlength => 20

    %p.checkbox_select
      = aspect.label :contacts_visible, t('aspects.edit.make_aspect_list_visible')
      = aspect.check_box :contacts_visible, :default => true

    %br

    = aspect.submit t('.create'), :class => 'button'

app/views/aspects/create.js.erb
//   Copyright (c) 2011, Diaspora Inc.  This file is
//   licensed under the Affero General Public License version 3 or later.  See
//   the COPYRIGHT file.

$('ul.dropdown_list[data-person_id=<%= @person.id %>] .newItem').before("<%= escape_javascript( render('aspect_memberships/aspect_dropdown_list_item', :aspect => @aspect, :person => @person, :contact => @contact)) %>");

ContactEdit.updateNumber("<%= @person.id %>");
$.facebox.close();
$('#profile .dropdown').toggleClass("active");

app/views/aspects/index.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :head do
  = include_javascripts :home
.span-15.append-2
  #aspect_stream_container
    = render 'aspect_stream',
      :aspect => @aspect,
      :aspect_ids => @aspect_ids,
      :posts => @posts

.span-7.leftBar.last
  #home_user_badge
    = owner_image_link
    %h3{:style => "position:relative;"}
      = current_user.name
      .description
        = link_to current_user.diaspora_handle, person_path(current_user.person)

  .section
    .title
      = image_tag('/images/icons/bookmark.png')
      %h5
        = t('bookmarklet.heading')
    .content
      != t('bookmarklet.explanation', :link => link_to(t('bookmarklet.explanation_link_text'), bookmarklet))

  .section
    .title
      = image_tag('/images/icons/cubbies.png')
      %h5
        = t('.cubbies.heading')
    .content
      = t('.cubbies.explanation')
      = link_to t('.cubbies.learn_more'), token_path

  - if @invites > 0
    .section
      .title

        = image_tag('/images/icons/plus.png')
        %h5
          .right
            = t('shared.invitations.invitations_left', :count => @invites)
          = t('shared.invitations.invite_your_friends')
      .content
        = render "shared/invitations", :invites => @invites

  %hr

  #aspect_listings.section
    = render 'aspects/aspect_listings', :aspects => @aspects

  - if @invites <= 0
    .section.invite_friends
      %h4= t('shared.invitations.invite_your_friends')
      = render "shared/invitations", :invites => @invites

app/views/aspects/index.js.erb
$('#aspect_stream_container').html("<%= escape_javascript(render('aspects/aspect_stream', :aspect => @aspect, :aspect_ids => @aspect_ids, :posts => @posts)) %>");
$('#aspect_listings').html("<%= escape_javascript(render('aspects/aspect_listings', :aspects => @aspects)) %>");
$('a[rel*=facebox]').facebox();

app/views/aspects/index.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#aspect_header
  - if @aspect == :all
    = t('all_aspects')
  - else
    = @aspect
  = link_to t('.post_a_message'), '#publisher_page', :id => 'publisher_button'


#main_stream.stream
  = render 'shared/stream', :posts => @posts
  -if @posts.length > 0
    #pagination
      %a.more-link.paginate{:href => next_page_path}
        %h2= t("more")
- content_for :subpages do
  = render 'shared/publisher', :aspect_ids => @aspect_ids

app/views/aspects/manage.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  = include_javascripts :aspects

- content_for :page_title do
  = t('.manage_aspects')

#section_header
  .right
    = link_to("+ #{t('.add_a_new_aspect')}", "#add_aspect_pane", :class => "new_aspect button", :title => t('.add_a_new_aspect'), :rel => 'facebox')

  %h2
    =t('.manage_aspects')

#manage_aspect_zones
  .span-24.last
    - for aspect in @aspects
      .aspect.span-9{:data=>{:guid => aspect.id}}
        .aspect_name
          %span.edit_name_field
            %h3{:contenteditable=>true, :ondragenter=>"return false;", :ondragleave=>"return false;", :ondragover=>"return false;", :ondrop=>"return false;"}
              = aspect.name
            %span.tip click to edit

          %ul.tools
            %li= link_to t('.add_a_new_contact'), "#manage_aspect_contacts_pane_#{aspect.id}", :class => 'manage_aspect_contacts_button', :rel => "facebox"
            %li!= remove_link(aspect)

        %ul.dropzone{:data => {:aspect_id => aspect.id}}
          -for contact in aspect.contacts
            %li.person{:data => {:guid => contact.person.id, :aspect_id => aspect.id}}
              .delete
                .x
                  X
                .circle
              = link_to person_image_tag(contact.person), contact.person
          .draggable_info
            =t('.drag_to_add')

          .facebox_content
            %div{:id => "manage_aspect_contacts_pane_#{ aspect.id}"}
              = render "requests/manage_aspect_contacts", :aspect => aspect, :manage => true, :contacts => @contacts

app/views/aspects/new.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= render 'new', :remote => true, :person_id => @person_id

app/views/aspects/toggle_contact_visibility.js.erb
$(document).ready(function() {

  var padlockImg = $("#contact_visibility_padlock");

  if(padlockImg.hasClass('open')) {
    padlockImg.attr('src', 'images/icons/padlock-closed.png');
    padlockImg.attr('title', "<%= t('aspects.edit.aspect_list_is_not_visible') %>");
  } else {
    padlockImg.attr('src', 'images/icons/padlock-open.png');
    padlockImg.attr('title', "<%= t('aspects.edit..aspect_list_is_visible') %>");
  }
  padlockImg.toggleClass('open');

});

app/views/aspects/update.js.erb
$(document).ready(function() {
  var newName = "<%= @aspect.name %>"
  $("#aspect_name").val( newName );
  $("*[data-guid='<%= @aspect.id %>']").find('.name').html( newName );
});